// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var React = require("react");
var CreateTodo = require("../CreateTodo.bs.js");
var ReactTestingLibrary = require("../external/ReactTestingLibrary.bs.js");

Jest.test("isEmpty when input is empty", (function (param) {
        return Jest.Expect.toBe(Jest.Expect.expect(CreateTodo.isEmpty("")), true);
      }));

Jest.test("isEmpty when input is not empty", (function (param) {
        return Jest.Expect.toBe(Jest.Expect.expect(CreateTodo.isEmpty("foo")), false);
      }));

Jest.test("Adding a todo", (function (param) {
        var handleCreate = function (_i) {
          
        };
        return Jest.Expect.toMatchSnapshot(Jest.Expect.expect(ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, React.createElement(CreateTodo.make, {
                                onCreate: handleCreate
                              })).container));
      }));

/*  Not a pure module */
