// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/rescript-jest/src/jest.bs.js");
var React = require("react");
var Header = require("../Header.bs.js");
var ReactTestingLibrary = require("../external/ReactTestingLibrary.bs.js");

Jest.test("displays text", (function (param) {
        return Jest.Expect.toMatchSnapshot(Jest.Expect.expect(ReactTestingLibrary.render(undefined, undefined, undefined, undefined, undefined, React.createElement(Header.make, {})).container));
      }));

/*  Not a pure module */
