// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Todos = require("./Todos.bs.js");
var React = require("react");
var Header = require("./Header.bs.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Dom_storage = require("rescript/lib/js/dom_storage.js");
var React$1 = require("@chakra-ui/react");

var theme = React$1.extendTheme({
  styles: {
    global: {
      "html, body": {
        fontFamily: "Playfair Display",
        fontSize: "xl"
      }
    }
  }
});

function App(Props) {
  var todos = React.useMemo(function () {
    return Belt_Option.map(Dom_storage.getItem("todos", localStorage), (function (prim) {
      return JSON.parse(prim);
    }));
  });
  return React.createElement(React$1.ChakraProvider, {
    children: null,
    theme: theme
  }, React.createElement(Header.make, {}), React.createElement(Todos.make, {
    todos: todos
  }));
}

var make = App;

exports.theme = theme;
exports.make = make;
/* theme Not a pure module */
