// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function CreateTodo(Props) {
  var onCreate = Props.onCreate;
  var match = React.useState(function () {
        return "";
      });
  var setValue = match[1];
  var value = match[0];
  var handleChange = function (e) {
    var t = e.target;
    Curry._1(setValue, (function (param) {
            return t.value;
          }));
  };
  return React.createElement("form", {
              onSubmit: (function (e) {
                  e.preventDefault();
                  Curry._1(onCreate, value);
                  Curry._1(setValue, (function (param) {
                          return "";
                        }));
                })
            }, React.createElement("div", {
                  className: "new-todo"
                }, React.createElement("input", {
                      id: "new-todo",
                      autoFocus: true,
                      placeholder: "new task",
                      value: value,
                      onChange: handleChange
                    }), React.createElement("button", {
                      role: "submit"
                    }, "add new task")));
}

var make = CreateTodo;

exports.make = make;
/* react Not a pure module */
