// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Header(Props) {
  return React.createElement("h1", undefined, "Maybe List");
}

var make = Header;

exports.make = make;
/* react Not a pure module */
