// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var React$1 = require("@chakra-ui/react");

function Header(Props) {
  return React.createElement(React$1.Box, {
              children: null,
              maxW: "500px",
              m: "auto"
            }, React.createElement(React$1.Text, {
                  children: "Maybe List",
                  textAlign: "center",
                  fontSize: "5xl"
                }), React.createElement(React$1.Text, {
                  children: "A todo app that deletes items if they haven't been completed in 24 hours.",
                  pt: 10
                }));
}

var make = Header;

exports.make = make;
/* react Not a pure module */
