// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Header = require("./Header.bs.js");
var ReactDom = require("react-dom");

var root = document.querySelector("#root");

if (!(root == null)) {
  ReactDom.render(React.createElement("div", undefined, React.createElement(Header.make, {})), root);
}

/* root Not a pure module */
