// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var App = require("./App.bs.js");
var React = require("react");
var Client = require("react-dom/client");

Client.createRoot(document.getElementById("root")).render(React.createElement(App.make, {}));

/*  Not a pure module */
