// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");

function Todo(Props) {
  var todo = Props.todo;
  var onClick = Props.onClick;
  var handleClick = function (__) {
    Curry._1(onClick, todo);
  };
  return React.createElement("li", undefined, todo.text, React.createElement("input", {
                  type: "checkbox",
                  onClick: handleClick
                }));
}

var make = Todo;

exports.make = make;
/* react Not a pure module */
