// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var TodoItem = require("./TodoItem.bs.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function toggleTodo(todos, todo) {
  var updatedTodo_text = todo.text;
  var updatedTodo_completed = !todo.completed;
  var updatedTodo_createdAt = todo.createdAt;
  var updatedTodo_id = todo.id;
  var updatedTodo = {
    text: updatedTodo_text,
    completed: updatedTodo_completed,
    createdAt: updatedTodo_createdAt,
    id: updatedTodo_id
  };
  return Belt_Array.concat(Belt_Array.keep(todos, (function (x) {
                    return x.id !== todo.id;
                  })), [updatedTodo]);
}

function Todos(Props) {
  var todos = Props.todos;
  var match = React.useState(function () {
        return todos;
      });
  var setItems = match[1];
  var handleClick = function (e) {
    var updatedTodo_text = e.text;
    var updatedTodo_completed = !e.completed;
    var updatedTodo_createdAt = e.createdAt;
    var updatedTodo_id = e.id;
    var updatedTodo = {
      text: updatedTodo_text,
      completed: updatedTodo_completed,
      createdAt: updatedTodo_createdAt,
      id: updatedTodo_id
    };
    Curry._1(setItems, (function (_items) {
            return Belt_Array.concat(Belt_Array.keep(_items, (function (x) {
                              return x.id !== e.id;
                            })), [updatedTodo]);
          }));
  };
  return React.createElement("ul", undefined, Belt_Array.map(match[0], (function (t) {
                    return React.createElement(TodoItem.make, {
                                todo: t,
                                onClick: handleClick,
                                key: String(t.id)
                              });
                  })));
}

var make = Todos;

exports.toggleTodo = toggleTodo;
exports.make = make;
/* react Not a pure module */
