// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Todo(Props) {
  var todo = Props.todo;
  return React.createElement("li", undefined, todo.text);
}

var make = Todo;

exports.make = make;
/* react Not a pure module */
