// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Todo = require("./Todo.bs.js");
var React = require("react");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

function Todos(Props) {
  var todos = Props.todos;
  return React.createElement("ul", undefined, Belt_Array.map(todos, (function (t) {
                    return React.createElement(Todo.make, {
                                todo: t
                              });
                  })));
}

var make = Todos;

exports.make = make;
/* Todo Not a pure module */
